version: "3"
services:
  complaint-portal:
    image: complaint-portal
    ports:
      - "8089:8087"
    networks:
      - cportal-mysql
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - cportaldb
 
  cportaldb:
    image: mysql:5.6
    networks:
      - cportal-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Naman@11396
      - MYSQL_USER=root
      - MYSQL_DATABASE=complaintportal
      

networks:
  cportal-mysql: 
